version: "3.8"
services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001"
    environment:
      - PUBLIC_NEXT_G_ANALYTICS_ID=${PUBLIC_NEXT_G_ANALYTICS_ID}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - portfolio-network
networks:
  portfolio-network:
    name: portfolio-network
