version: "3.9"
services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
      ports:
        - "3001:3001"
      
      env_file:
        - ./.env

      volumes:
        - .:/app
      networks:
        - proxy
networks:
  proxy:
    external: true