version: "3.8"
services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - PUBLIC_NEXT_G_ANALYTICS_ID =${PUBLIC_NEXT_G_ANALYTICS_ID}
    volumes:
      - .:/app
    networks:
      - proxy
networks:
  proxy:
    external: true
